name: myretro-service
networks:
  reverse_proxy_network:
    external: true
volumes:
  pocketbase-data: null
services:
  myretro-front:
    image: andreuro/myretro:latest
    container_name: myretro
    networks:
      - reverse_proxy_network
    ports:
      - 127.0.0.1:3000:3000
  pocketbase:
    image: andreuro/myretropocket:0.0.1
    container_name: myretropocket-db
    networks:
      - reverse_proxy_network
    ports:
      - 127.0.0.1:8090:8090
    volumes:
      - pocketbase-data:/pb/pb_data